### ISSUE TITLE
Verify packet is valid JSON

### ISSUE THREAD

**Issue by NikoGrano** [GameTactic/CPP-Echo#18]
All data coming to server must me valid JSON as defined in https://tools.ietf.org/html/rfc7159

**Comment by bryansamuel1** [comment]
isn't data transferred to and from the server as strings? I JSON stringify and parse my objects atm

**Comment by NikoGrano** [comment]
Yes. However adding and remocing data on the server I need to do parsing also. Invalid json will cause core dump, so need to first verify it is valid json before letting it pass.

**Comment by bryansamuel1** [comment]
so I don't need to stringify it then? just parse what the server sends me?

**Comment by NikoGrano** [comment]
Well, you will still need to do it as far I know.

**Comment by NikoGrano** [comment]
Implemented in https://github.com/GameTactic/CPP-Echo/commit/7a1b174b8a9520dd6ed9e5fefd24092ca25c19a0
