### ISSUE TITLE
Make server port configurable.

### ISSUE THREAD

**Issue by NikoGrano** [GameTactic/CPP-Echo#4]
Currently server is started on port 80 by default. Please add option to add argument on start to configure port and add documentation about it.

This should be done by passing int to EchoServer class constructor.

**Comment by btheteach** [comment]
I will work on this

**Comment by NikoGrano** [comment]
Thank you!

**Comment by NikoGrano** [comment]
@Jean-BaptisteTheSage I see you as inactive. Please confirm. For now I will remove you from this issue.
