### ISSUE TITLE
Undefined behavior

### ISSUE THREAD

**Issue by Loki-Astari** [GameTactic/CPP-Echo#7]
Running the main event loop from inside the constructor of `EchoServer` will result in undefined behavior.

Technically the object `srv` define [here](https://github.com/GameTactic/CPP-Echo/blob/master/src/main.cpp#L149) is not live until **after** the constructor completes.

See: n4800 Section 6.6.3 Object and reference lifetime [basic.life] Paragraph 1:

> The lifetime of an object or reference is a runtime property of the object or reference. An object is said to have non-vacuous initialization if it is of a class or array type and it or one of its subobjects is initialized by a constructor other than a trivial default constructor. [Note: Initialization by a trivial copy/move constructor is non-vacuous initialization. —end note] The lifetime of an object of type T begins when:  
> (1.1) — storage with the proper alignment and size for type T is obtained, and . 
> (1.2) — if the object has non-vacuous initialization, **its initialization is complete**,

Therefore using `this` as callback parameters is not valid (as you can not call member function on an objects lifespan had not begun or ended.

Thus you should remove from the constructor the following:

            // Start the server.
            _server.start_accept();
            _server.run();

Though you can place this in a new method probably called `run`.

**Comment by NikoGrano** [comment]
Thank you. Great explanation also!

**Comment by NikoGrano** [comment]
Resolved by #8
