### ISSUE TITLE
Signal Handlers are not async safe

### ISSUE THREAD

**Issue by Loki-Astari** [GameTactic/CPP-Echo#9]
A signal handler is allowed to do very little.  
You definitely can not call any code that as not async safe (as signal handlers can potentially be nested).

> The C Standard, 7.14.1.1, paragraph 5 [ISO/IEC 9899:2011], states that if the signal occurs other than as the result of calling the abort() or raise() function, the behavior is undefined if

    ...the signal handler calls any function in the standard library other than the abort function, the _Exit function, the quick_exit function, or the signal function with the first argument equal to the signal number corresponding to the signal that caused the invocation of the handler.

See also: http://man7.org/linux/man-pages//man7/signal-safety.7.html

As a result you can not use any high level IO routines (especially things like std::cout/std::cerr) from within a signal handler. Though you can use some of the lower level calls (like `write()`) but you should create any message first (not using dynamic allocation).

**Comment by NikoGrano** [comment]
@Loki-Astari Sorry, I had to revert this due.

```
-- Build files have been written to: /compile

Scanning dependencies of target server

[ 50%] Building CXX object src/CMakeFiles/server.dir/main.cpp.o

/compile/src/main.cpp: In function 'void signalHandler(int)':

/compile/src/main.cpp:159:35: error: 'sizeog' was not declared in this scope

write(STDOUT_FILENO, message, sizeog(message));

^~~~~~

/compile/src/main.cpp:159:35: note: suggested alternative: 'size_t'

write(STDOUT_FILENO, message, sizeog(message));

^~~~~~

size_t

make[2]: *** [src/CMakeFiles/server.dir/build.make:63: src/CMakeFiles/server.dir/main.cpp.o] Error 1

make[1]: *** [CMakeFiles/Makefile2:91: src/CMakeFiles/server.dir/all] Error 2

make: *** [Makefile:130: all] Error 2

```

Could you take a look and resubmit the PR.

**Comment by NikoGrano** [comment]
Thank you!
